<?php
/**
 * @file
 * term_id_field_formatter module main file.
 */

/**
 *  Implements hook_field_formatter_info().
 */
function term_id_field_formatter_field_formatter_info() {
  return array(
    'taxonomy_field_formatter_id' => array(
      'label' => t('ID'),
      'field types' => array('taxonomy_term_reference'),
    ),
  );
}

/**
 *  Implements hook_field_formatter_view().
 */
function term_id_field_formatter_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  if($display['type'] == 'taxonomy_field_formatter_id') {
    foreach($items as $delta => $item) {
      $element[$delta] = array(
        '#markup' => $item['tid'],
      );
    }
  }

  return $element;
}